### ISSUE TITLE
Odd behavior when items is removed from array.

### ISSUE THREAD

**Issue by andwah** [PuppetJs/puppet-polymer-client#10]
If items is removed from an array (server side). the client-side is not 100% accurate.

If 2nd item is removed then the result will be more obvious 

To test:
1. Run this app https://github.com/Starcounter/Warehouse with the latest Starcounter together with the `Sign In` app

2. Sign in with "admin/admin"
3. Click the `TEST NOTICE` button, 2-3 times. (notices will appear at the top of the screen)
4. Close the notice the 2second notice, then try closing the next (it will not close).

![image](https://cloud.githubusercontent.com/assets/2656996/13497293/e1164938-e154-11e5-855a-9bfefe8e28ee.png)

Another test:
1. Click the `RESET (WITH SAMPLE DATA)` wait or result.
2. click again `RESET (WITH SAMPLE DATA)` wait or result.

Not the List of "Organizations" is messed up. Each time you press you will get three new items in the list, The list should only have three item's

![image](https://cloud.githubusercontent.com/assets/2656996/13497397/642e093c-e155-11e5-9c9e-f076127a8092.png)

**Comment by warpech** [comment]
Both cases reproducible for me. I will investigate tomorrow.

**Comment by warpech** [comment]
I will be posting a fix before lunch.

**Comment by warpech** [comment]
Fix available in https://github.com/StarcounterSamples/sysupgrade

I will push to Starcounter later today

**Comment by warpech** [comment]
Fixed, released a new version. Available immediately in SysUpgrade as well as in the next Starcounter nightly.
