### ISSUE TITLE
ignoreAdd is not compiled to a RegExp

### ISSUE THREAD

**Issue by warpech** [PuppetJs/puppet-polymer-client#11]
@malx122 reports that `ignore-add` attribute is passed to PuppetJs as a string, but not compiled to a RegExp.

In result, there is an exception saying that `test` is not defined in https://github.com/PuppetJs/PuppetJs/blob/501e82509b1b63a761167b047644977ceb18392e/src/puppet.js#L511

Probably related to: https://github.com/PuppetJs/puppet-polymer-client/issues/3

Might be fixed by: https://github.com/PuppetJs/puppet-polymer-client/issues/9

**Comment by warpech** [comment]
The above commit fixes the problem. It seems that Polymer doesn't have any type casting or guarding. Even though `this.ignoreAdd` is declared as RegExp, it happily accepts being set to string, which was causing the problem.

@tomalec are you ok with this change?

**Comment by warpech** [comment]
Fixed, released a new version. Available immediately in SysUpgrade as well as in the next Starcounter nightly.

**Comment by tomalec** [comment]
LGTM
