### ISSUE TITLE
Templates in Shadow DOM are not notified

### ISSUE THREAD

**Issue by warpech** [PuppetJs/puppet-polymer-client#12]
`puppet-polymer-client` only notifies templates that are in light DOM:

https://github.com/PuppetJs/puppet-polymer-client/blob/495464e151796a4f952a21d1caa807c874d57d3b/puppet-client.html#L235

```
var templates = document.querySelectorAll("template[is=dom-bind]");
```

Which is a problem for @malx122, who has a modal window contents rendered in a Polymer element.

I will try to upgrade `starcounter-include` to us Polymer notification mechanism.

**Comment by warpech** [comment]
Above commit contains a initial solution that uses Polymer's notification protocol to notify about remote changes instead of document.querySelectorAll("template[is=dom-bind]")

Tests and comments welcome

**Comment by warpech** [comment]
The solution requires `starcounter-include`, `launcher-include`, `imported-template` to implement wrapping for Polymer's `_notifyPath` as seen in https://github.com/StarcounterSamples/SysUpgrade/commit/f9e40c76b87d93de215bee64f854b4d39317b8d4

@tomalec do you agreee this is a way to go?

**Comment by malx122** [comment]
Sorry that I havn't been able to test it yet. Will try to find time tonight

**Comment by tomalec** [comment]
I really like the approach to reduce our own magic, and just forward Polymers notification protocol. @warpech Could you just add some comments on those methods, so it would be easier to maintain, and we will do not have to support it once Polymers templating engine will change. I would also be great to have test case for this.

**Comment by warpech** [comment]
Fixed with the above fixes. Will be available in the next Starcounter nightly.
