### ISSUE TITLE
Side effect or feature of puppet-polymer-client

### ISSUE THREAD

**Issue by miyconst** [PuppetJs/puppet-polymer-client#13]
I just have discovered that with `puppet-polymer-client` we can add custom binding values to `<template is="dom-bind">` outside of `model`.

```html
<template is="dom-bind">
    <p>{{model.RawData}}</p>
    <custom-parser data="{{model.RawData}}" parsed-items="{{parsedItems}}"></custom-parser>
    <template is="dom-repeat" items="{{parsedItems}}">
        <p>{{item.Name}}</p>
    </template>
</template>
```

The `parsedItems` collection filled by `<custom-parse>` works aside `model` without any issues.

This is not the case with `dom-bind-notifier`, it is trying to apply `parsedItems` changes on top of `model` and fails.

Personally I like this feature, but because of it FileUpload example does not work with `dom-bind-notifier`.

@warpech, @tomalec what do you think?

**Comment by warpech** [comment]
I think it is a good use of puppet, not even a side effect. Good finding!

**Comment by miyconst** [comment]
Good. Then I close this issue and don't fix the file upload example to work with the old version.
