### ISSUE TITLE
Patches don't get applied to arrays of primitives

### ISSUE THREAD

**Issue by joozek78** [PuppetJs/puppet-polymer-client#17]
If your view-model would have an array of primitive values, then patches won't get applied to DOM. This is caused by bug in Polymer: Polymer/polymer#3377

See tests in `test/d-b-n_smoke/arrays.html` (search for 'issues/17')

**Comment by warpech** [comment]
Turns out to be a clone of https://github.com/PuppetJs/puppet-polymer-client/issues/14

**Comment by joozek78** [comment]
See #14 for real-life example

**Comment by tomalec** [comment]
In our case it seems it's not just an array of primitives problem, it also affect arrays of objects.

However I figured out it might not ma a Polymer's issue, but ours. I'm still investigating.

**Comment by tomalec** [comment]
I will mark it as done, as in general we clearly are applying patches for arrays of primitives. 

#14 seems to be very narrow use case (described https://github.com/PuppetJs/puppet-polymer-client/issues/14#issuecomment-222372565), so we could track it there.
