### ISSUE TITLE
puppet-polymer-client is not 100% compatible with puppet-client api

### ISSUE THREAD

**Issue by miyconst** [PuppetJs/puppet-polymer-client#2]
The `puppet-client` has `network` property which we use in SignIn and Registration app to change state.

The `puppet-polymer-client` does not have this property and I should navigate like `puppet.network`. I have changed the Registration app, but maybe we should add this property to `puppet-polymer-client` itself?

**Comment by warpech** [comment]
Because of that, @tomalec made some modifications of `starcounter-debug-aid` already: https://github.com/StarcounterSamples/starcounter-debug-aid/commit/dc450856b461b858018d6a70ba94a6be609f58c7

But I think there is not problem to add `network` property to puppet-polymer-client.

**Comment by miyconst** [comment]
So, do you think it's better to just add this after https://github.com/PuppetJs/puppet-polymer-client/blob/gh-pages/puppet-client.html#L191 or modify out existing apps?

```js
this.network = this.puppet.network;
```

**Comment by tomalec** [comment]
Simply `puppet-polymer-client` is not a Puppet instance, because of conflict in method names between `P0lymer.Base` and `EventTarget`. The puppet instance for p-p-c is at `.puppet`.

@warpech had an idea to remove Event API from puppet, then we could probably make it an instance back again.

**Comment by warpech** [comment]
That's the proposal mentioned by @tomalec: https://github.com/PuppetJs/PuppetJs/issues/78

**Comment by miyconst** [comment]
Added the `this.network` property.
