### ISSUE TITLE
Improve "Reload page" link at mobile

### ISSUE THREAD

**Issue by Mnosek** [PuppetJs/puppet-polymer-client#35]
Currently we develop a mobile app for Sweoffshore. After some UX testing we found out that it is very hard to tap "Reload page" button if there is connection error on a mobile (See a screenshot below). IMO there are two issues:
- Link is to small
- It is too much sticked to the top.

My proposal is to create something what feels more like a button an move it to the second, separate line.

![2016-10-09 15 02 02](https://cloud.githubusercontent.com/assets/4943949/19221359/41cd3d0a-8e42-11e6-8525-119ba0bd71aa.png)

cc @joozek78

**Comment by Mnosek** [comment]
cc @tomalec @warpech - do you have any idea about that? We need to figure out something :)

**Comment by tomalec** [comment]
I like the idea of bigger button for smaller screen sizes.

**Comment by warpech** [comment]
My proposal is to do two things: 

1. Change the link thext "Reload page" to "Click here to reload"
2. Make the whole red area a link, not just that text

Then we will not have to have a separate version for mobile.

Like this:

<img width="362" alt="2016-11-02 12_16_37-kitchensink" src="https://cloud.githubusercontent.com/assets/566463/19926723/64cf1fe6-a0f6-11e6-8f6d-cf5ef21f3b56.png">

**Comment by Mnosek** [comment]
Merged at #36. Thanks guys for the input!
