### ISSUE TITLE
Remove array item removes multiple items at a time

### ISSUE THREAD

**Issue by miyconst** [PuppetJs/puppet-polymer-client#4]
The following gif demonstrates the issue:

![polymer-array-bug](https://cloud.githubusercontent.com/assets/6435556/13432948/0fb7da1c-dfd0-11e5-80f6-d1f054958bbf.gif)

The patch to remove an item received from server:

```json
[{"op":"replace","path":"/_ver#s","value":15},{"op":"test","path":"/_ver#c$","value":14},{"op":"remove","path":"/SubPage/Playground/Items/7"}]
```

The test bench is available here: https://github.com/miyconst/Playground/

**Comment by warpech** [comment]
Fix released in next Starcoutner nightly. Thanks for reporting!
