### ISSUE TITLE
Custom elements with array parameters are not being notified about array changes

### ISSUE THREAD

**Issue by miyconst** [PuppetJs/puppet-polymer-client#5]
I have a model:

```json
{
    "Items": []
}
```

And view:

```html
<template is="dom-repeat" items="{{model.Items}}">
    <div>{{item.Name}}</div>
</template>
<ct-list list-items="{{model.Items}}"></ct-list>
```

When server updates the `Items` array the changes are reflected in the `dom-repeat`, but not in `ct-list`.

Exactly same setup works fine with `Polymer 1.1.5` + `dom-bind-notifier`.

Test bench is available here: https://github.com/miyconst/Playground/.
To downgrade to `Polymer 1.1.5` rename `sys-downgrade` folder to `sys`.

**Comment by warpech** [comment]
Reproducible for me as well. I will take a look.

**Comment by warpech** [comment]
Fix released in next Starcoutner nightly. Thanks for reporting!
