### ISSUE TITLE
morphUrl is undefined

### ISSUE THREAD

**Issue by warpech** [PuppetJs/puppet-polymer-client#8]
@mattiasmak showed me today that the following line does not work with puppet-polymer-client:

```
var puppet = document.querySelector('puppet-client');
puppet.morphUrl(url);
```

Because morphUrl is now available at `puppet.puppet`.

This is the same problem as with: https://github.com/PuppetJs/puppet-polymer-client/issues/2 (and https://github.com/PuppetJs/puppet-polymer-client/issues/3 to an extent).

**Comment by warpech** [comment]
@tomalec do you have an idea how to fix the API compatibility problems at once?

**Comment by tomalec** [comment]
Inherit from Puppet as before

**Comment by warpech** [comment]
First, I will apply a quick fix:

```js
			this.network = this.puppet.network;
+			this.morphUrl = this.puppet.morphUrl.bind(this.puppet);
```

Extending Puppet can be tracked as a separate issue.

**Comment by warpech** [comment]
Fixed and released in SysUpgrade and the next Starcounter nightly

Inheritance from Puppet will be tracked in a separate issue
