### ISSUE TITLE
Inherit from Puppet

### ISSUE THREAD

**Issue by warpech** [PuppetJs/puppet-polymer-client#9]
As stated in issues: https://github.com/PuppetJs/puppet-polymer-client/issues/2 and  https://github.com/PuppetJs/puppet-polymer-client/issues/8, there is some incompatibilities with the original puppet-client, which was inheriting from Puppet. 

They can be fixed if puppet-polymer-client inherits from Puppet as well. 

@tomalec proposes to inherit `puppet-polymer-client`'s prototype from Puppet's prototype if I understand correctly.

**Comment by warpech** [comment]
This should automatically fix #3 if done property.

**Comment by warpech** [comment]
Assigning to @joozek78. Please follow the development instructions in https://github.com/PuppetJs/puppet-polymer-client#development

**Comment by warpech** [comment]
While discussing this with @joozek78 and @aloscha, we decided that OP contradicts https://github.com/PuppetJs/PuppetJs/issues/85#issuecomment-221882278. The latter is much more important.

This is a pity, since @joozek78 already has a solution for OP, but let's not merge it and try fixing PuppetJs issue 85 instead.

**Comment by tomalec** [comment]
How it contradicts?

**Comment by warpech** [comment]
The idea is that `puppet-polymer-client` should wrap PuppetJs, not pretend that it is the same thing. Otherwise we ask for problems like this https://github.com/PuppetJs/PuppetJs/issues/85

Similarly how, these components are wrappers: https://github.com/Juicy/juicy-markdown, https://github.com/Juicy/juicy-ace-editor/blob/gh-pages/juicy-ace-editor.html

**Comment by warpech** [comment]
Discussed this again with @joozek78, now after he finished work on https://github.com/PuppetJs/PuppetJs/issues/85, we still think that work done on this is not worth merging. We are keeping the https://github.com/PuppetJs/puppet-polymer-client/tree/extend_puppet branch for future reference.
